//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBluejackCake_Group4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cake
    {
        public int CakeId { get; set; }
        public string CakeName { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Picture { get; set; }
    }
}
