//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBluejackCake_Group4
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string CustomerName { get; set; }
        public string CakeName { get; set; }
        public Nullable<int> CakePrice { get; set; }
        public string ChocolatePlateGreeting { get; set; }
        public string PromotionTitle { get; set; }
        public Nullable<int> PromotionDiscount { get; set; }
        public Nullable<int> SubTotal { get; set; }
    }
}
